### ISSUE TITLE
Unhandled exception on MCU during proxy call

### ISSUE THREAD

**Issue by tolauwae** [TOPLLab/WARDuino#102]
When trying to call `$env.chip_digital_read` as a proxy in the button example (of the plugin) the mcu crashes due to an unhandled exception.

The emulator reads the following on the serial bus:

```
proxy: arg 0: i32 value 26
proxy: Guru Meditation Error: Core 1 panic'ed (LoadProhibited). Exception was unhandled.
```

**Comment by tolauwae** [comment]
The exception occurs somewhere after the `Debugger::handleProxyCall` method returns.

@carllocos any ideas what this could be?

**Comment by carllocos** [comment]
The issue occurs in branch [feat/wood](ce0b417ae427d642743d6d3a801cd390664d6bd4)
