### ISSUE TITLE
Sleep main thread during pause

### ISSUE THREAD

**Issue by tolauwae** [TOPLLab/WARDuino#145]
Sleep main thread during pause until dbg message is received, instead of repeating loop.

**Comment by tolauwae** [comment]
+ Use a `condition_variable` from `std::thread` to sleep until a debug message is received on the other thread.
+ Wake up thread when the program needs to exit early.

**Comment by carllocos** [comment]
I believe this [PR](https://github.com/TOPLLab/WARDuino/pull/147) completes this feature. If not @tolauwae please reopen this thread.
