### ISSUE TITLE
WebSocket starts a socketserver instead of a socketclient

### ISSUE THREAD

**Issue by carllocos** [TOPLLab/WARDuino#149]
When you start the emulator with option `--proxy portnumber`. The VM creates an object of type `WebSocket` which is meant to be used as the client side socket that connects to a remote socket server running on the MCU. The socket connection is supposed to be used for proxy call and the pushing of events.

However,  when opening the created WebSocket object via `WebSocket::open`, the object starts a socket server instead of establishing a connection to the remote server as one would expect.

**Comment by tolauwae** [comment]
Version [0.5.0](https://github.com/TOPLLab/WARDuino/releases/tag/v0.5.0) just released with this fix.
