### ISSUE TITLE
Integrating Disco-VM branch into Main

### ISSUE THREAD

**Issue by carllocos** [TOPLLab/WARDuino#150]
Anticipated tasks needed to integrate [disco-vm branch](https://github.com/TOPLLab/WARDuino/tree/disco-vm) into the main

- [ ] printing and updating state as explained here https://github.com/TOPLLab/WARDuino/issues/127
   - [X] globals https://github.com/TOPLLab/WARDuino/pull/151
   - [X] Stack values https://github.com/TOPLLab/WARDuino/pull/155
- [ ] https://github.com/TOPLLab/WARDuino/issues/126
- [ ] keeping track of errors on fail
- [ ] Wifi communication

**Comment by tolauwae** [comment]
We should split these different changes into separate branches with each their own PR.

**Comment by tolauwae** [comment]
Closing since this is superseded by the discussion.
