### ISSUE TITLE
Trap on incorrect callbacktype signature

### ISSUE THREAD

**Issue by carllocos** [TOPLLab/WARDuino#175]
Currently, a callback of any type signature can be subscribed via primitive [`subscribe_interrupt`](https://github.com/TOPLLab/WARDuino/blob/6cd2bf610d8b1cb87b0178f886360cf3cd6435de/src/Primitives/arduino.cpp#L606) . This is a problem because the callback handler expects the registered callback to take 5 arguments given that it pushes 5 stack values prior handling of an event:

As a result

**Comment by tolauwae** [comment]
This is exactly this feature request: https://github.com/TOPLLab/WARDuino/issues/86
And this TODO: https://github.com/TOPLLab/WARDuino/blob/6cd2bf610d8b1cb87b0178f886360cf3cd6435de/src/WARDuino/CallbackHandler.cpp#L210-L212
