### ISSUE TITLE
step does not advance when bp reached

### ISSUE THREAD

**Issue by carllocos** [TOPLLab/WARDuino#18]
Since the solution on [issue 5](https://github.com/TOPLLab/WARDuino/issues/5), the "step" interrupt no longer advances after reaching a breakpoint . The cause is the following if 

[https://github.com/TOPLLab/WARDuino/blob/3f349ed7e9506b1f00113ba1375520294d91608e/instructions.cpp#L1498](https://github.com/TOPLLab/WARDuino/blob/3f349ed7e9506b1f00113ba1375520294d91608e/instructions.cpp#L1498)

when a breakpoint is reached and you step the branch condition evaluates to true.

**Comment by beardhatcode** [comment]
Would this be solved by also putting these lines in the step case?\

https://github.com/TOPLLab/WARDuino/blob/3f349ed7e9506b1f00113ba1375520294d91608e/interrupt_operations.cpp#L257-L260

**Comment by carllocos** [comment]
Yes certainly! I'll make a PR later for that fix.

**Comment by tolauwae** [comment]
I believe this has been merged. Closing issue.
