### ISSUE TITLE
Push debugging

### ISSUE THREAD

**Issue by tolauwae** [TOPLLab/WARDuino#58]
- [x] second socket connection on drone
- [x] drone version of `CallbackHandler::push_event`: sends event to emulator (as json)
- [x] emulator: receive data from second socket connection (while loop in new thread)
- [x] emulator: parse json data from socket and create `Event`
- [x] emulator: push events to event queue (`CallbackHandler::push_event`)
- [x] emulator: resolve event on message (plugin can choose when to resolve the event)
- [x] plugin: add command to perform next event
- [x] plugin: view current event queue
- [x] emulator: change event queue size
- [x] drone: add interrupt to toggle eventPushingMode
- [x] emulator: change proxy list at runtime
- [x] emulator: change the pushClient's buffer size
- [x] plugin: test push event receive
- [x] plugin: resolve next event
- [x] #62
---

json interface:

```json
{
   "topic":"topic string",
   "payload":"payload as a string"
}
```

**Comment by carllocos** [comment]
Reminder: sending events as JSON may increase the probability for the *probe effect*. In the future, we should opt for something less expensive (e.g., binary).
