### ISSUE TITLE
Off by one error with breakpoints

### ISSUE THREAD

**Issue by beardhatcode** [TOPLLab/WARDuino#7]
When debugging larger files, the offset reported by warduino is sometimes wrong (off by one)

The cause is probably somewhere here:

https://github.com/TOPLLab/WARDuino/blob/07cf2b6d32a38012753584500e85b51c4d5831da/WARDuino.cpp#L314-L327

https://github.com/TOPLLab/WARDuino/blob/07cf2b6d32a38012753584500e85b51c4d5831da/WARDuino.cpp#L335-L339

@carllocos could you supply 2 files: one with correct offset, one with a wrong offset

**Comment by carllocos** [comment]
In the factorial case the one byte offset does not occur, while in the tictactoe case it does. From the messing around with web assembly examples, I noticed that it starts once I start defining relatively long examples.
[examples.zip](https://github.com/TOPLLab/WARDuino/files/6050588/examples.zip)

**Comment by carllocos** [comment]
This did not occur anymore. Closing the issue
